# datos_alumnos.py

alumnos = [
    "Alvarez Chaparro, Ithzel",
    "Angeles Mendoza, Julio Cesar",
    "Arellano Domínguez, Adam Dave",
    "Arreola Yáñez, Maria Estrella",
    "Becerra Rebollo, Antonio",
    "Blancas Garcia, Paulo Caleb",
    "Bonilla Ponce, Cristian Octavio",
    "Breña Andalon, Carlos Antonio",
    "Carrillo Torres, Eric Daniel",
    "Chaparro Resendiz, Daniel",
    "Cuellar Jiménez, Carlos Santiago",
    "Cuevas Corona, Itzel",
    "Cuevas Rueda, Domingo Gabriel",
    "Durán Niembro, Valentina",
    "Escobar Bañuelos, Daniel",
    "Espinoza Esquivel, Vania Sophia",
    "Franco Valtierra, Tessa Pamela",
    "Gonzalez Ochoa, Cesar",
    "González Rosales, José Francisco",
    "Gutierrez Luna, Luis Hugo Samuel",
    "Gutierrez Luna, Sophia Stephanie",
    "Jimenez Rocha, Francisco Javier",
    "Leon Uribe, Evelyn Itzel",
    "Lopez Resendiz, Angel Johanis",
    "Mariño Munguia, Alejandro",
    "Martinez Avalos, Naomi Gisselle",
    "Martinez Santiago, Hector",
    "Montes Cardona, Jorge Leonardo",
    "Nolasco Vargas, Cristian Alejandro",
    "Orona Loera, Filiberto",
    "Quintanar Dominguez, Alberto",
    "Reynoso Rodriguez, Luis Eduardo",
    "Robles Moreno, Dayana Lizett",
    "Romero Alfaro, Eric Eduardo",
    "Ruiz Maldonado, Owen",
    "Sanabria Martinez, Diego",
    "Sanchez Galvan, Vanessa Fernanda",
    "Sezati Posada, Cristopher",
    "Tintori Krieg, Ana Pamela",
    "Villarreal Pasaran, Aldo",
]